### ISSUE TITLE
Not working on OSX 10.10.1

### ISSUE THREAD

**Issue by chiedojohn** [tmux-plugins/tmux-resurrect-auto#1]
Hey bruno!
I attempted to set this up on my Mac with OSX 10.10.1.

I have the following config file:

```
# This allows copy and paste in vim, etc. to work with tmux
#if-shell "uname | grep -q Darwin" "set-option -g default-command 'reattach-to-user-namespace -l zsh'"


setw -g mode-mouse on
set -g mouse-select-pane on
set -g mouse-resize-pane on
set -g mouse-select-window on
set -g mode-keys vi

# force a reload of the config file
unbind r
bind r source-file ~/.tmux.conf

bind L resize-pane -L 5 
bind D resize-pane -D 5 
bind U resize-pane -U 5 
bind R resize-pane -R 5

#### COLOUR (Solarized 256)

# default statusbar colors
set-option -g status-bg colour235 #base02
set-option -g status-fg colour136 #yellow
set-option -g status-attr default

# default window title colors
set-window-option -g window-status-fg colour244 #base0
set-window-option -g window-status-bg default
#set-window-option -g window-status-attr dim

# active window title colors
set-window-option -g window-status-current-fg colour166 #orange
set-window-option -g window-status-current-bg default
#set-window-option -g window-status-current-attr bright

# pane border
set-option -g pane-border-fg colour235 #base02
set-option -g pane-active-border-fg colour240 #base01

# message text
set-option -g message-bg colour235 #base02
set-option -g message-fg colour166 #orange

# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange

# clock
set-window-option -g clock-mode-colour colour64 #green


# VIM COPY AND PASTE BINDINGS BELOW.
# To enter copy mode, press {prefix} esc
# Use vim keybindings in copy mode
setw -g mode-keys vi
# Setup 'v' or 'V' to begin selection as in Vim
unbind [
bind Escape copy-mode

bind -t vi-copy v begin-selection
bind -t vi-copy V rectangle-toggle # `V` changes between line- and columnwise selection

# Clear scrollback. {prefix} Cntrl K
bind -n C-k clear-history

#Allow tmux Resurrect - prefix then ctrl-s to save. prefix then ctrl-r to restore
run-shell ~/.tmux/tmux-resurrect/resurrect.tmux
# Auto run tmux ressurect every 15 minutes and auto ressurect when opening a new window
run-shell ~/.tmux/tmux-resurrect-auto/resurrect_auto.tmux
# Allow tmux to select text, etc.
run-shell ~/.tmux/tmux-copycat/copycat.tmux
# tmux yank. Enable copy selected text to the clipboard. Needs the above with prefix + y.
run-shell ~/.tmux/tmux-yank/yank.tmux
# Make tmux auto resurrect start on restart computer
set -g @resurrect-auto-tmux-start 'on'
set -g @resurrect-auto-restore 'on'
```

Below is an example of my last tmux resurrect save:
```
pane	0	0	:bash	1	:*	0	:/Users/username	1	bash	:
pane	1	0	:bash	1	:*	0	:/Users/username	1	bash	:
pane	1	0	:bash	1	:*	1	:/Users/username	0	bash	:
window	0	0	1	:*	ae5d,80x23,0,0,0
window	1	0	1	:*	ce0e,142x31,0,0[142x15,0,0,1,142x15,0,16,2]
state	1	
```

Both auto-tmux-start and auto-restore are not working.

Let me know your thoughts!

**Comment by bruno-** [comment]
Hey, thanks for trying the plugin out.
The only thing that looks suspicious is the placement of `set -g @resurrect-auto-tmux-start 'on'`, `set -g @resurrect-auto-restore 'on'` settings.
Can you please try placing them along with other `set` options in your `tmux.conf`.

The trick is to make `run-shell plugin` run \*last*. That way, all the options are set \*before* plugins are ran.
Please let me know if that works!

**Comment by chiedojohn** [comment]
Hey man,
No problem! Thanks for writing it!

I made ```run-shell plugin``` run last but still no luck.

**Comment by bruno-** [comment]
Hm.. okay. Hopefully you'll have patience to do a little bit debugging. I'm surprised that both "tmux auto start" and "auto restore" features are not working.

What's the output of these when run from the shell:

- `tmux show -g @resurrect-save-script-path`
- `tmux show -g @resurrect-restore-script-path`
- `cat ~/Library/LaunchAgents/Tmux.Start.plist` (this is the file that should make tmux start after the computer is turned on)

Let's see if that gives us any clue what's wrong..

**Comment by chiedojohn** [comment]
Haha, no problem at all man. It's not like I'm paying you! :P
When I run ```tmux show -g @resurrect-save-script-path``` I get
- @resurrect-save-script-path "/Users/username/.tmux/tmux-resurrect/scripts/save.sh"
When I run ```tmux show -g @resurrect-restore-script-path``` I get
@resurrect-restore-script-path "/Users/username/.tmux/tmux-resurrect/scripts/restore.sh"
When I run ```cat ~/Library/LaunchAgents/Tmux.Start.plist``` I get
- /Users/username/Library/LaunchAgents/Tmux.Start.plist: No such file or directory

Maybe we're on to something with that last one? At what point should Tmux.Start.plist be getting created?

Thanks again!

**Comment by bruno-** [comment]
Hey - yes, we're onto something with the last one! The output for the first 2 commands is okay.

If this is present `set -g @resurrect-auto-tmux-start 'on'`, `Tmux.Start.plist` file should be created after `tmux.conf` is reloaded. Maybe I didn't document that well in  the [docs here](https://github.com/tmux-plugins/tmux-resurrect-auto/blob/master/scripts/handle_tmux_automatic_start/README.md). Tmux conf is reloaded with this shell command: `tmux source-file ~/.tmux.conf`.

**Comment by chiedojohn** [comment]
That's progress!
I ran ```tmux source-file ~/.tmux.conf.``` earlier and did again just now but the Tmux.Start.plist doesn't get created after I run that command.

You want to give it a shot with my config? The update config is now below
```
# This allows copy and paste in vim, etc. to work with tmux
#if-shell "uname | grep -q Darwin" "set-option -g default-command 'reattach-to-user-namespace -l zsh'"


setw -g mode-mouse on
set -g mouse-select-pane on
set -g mouse-resize-pane on
set -g mouse-select-window on
set -g mode-keys vi

# force a reload of the config file
unbind r
bind r source-file ~/.tmux.conf

bind L resize-pane -L 5 
bind D resize-pane -D 5 
bind U resize-pane -U 5 
bind R resize-pane -R 5

#### COLOUR (Solarized 256)

# default statusbar colors
set-option -g status-bg colour235 #base02
set-option -g status-fg colour136 #yellow
set-option -g status-attr default

# default window title colors
set-window-option -g window-status-fg colour244 #base0
set-window-option -g window-status-bg default
#set-window-option -g window-status-attr dim

# active window title colors
set-window-option -g window-status-current-fg colour166 #orange
set-window-option -g window-status-current-bg default
#set-window-option -g window-status-current-attr bright

# pane border
set-option -g pane-border-fg colour235 #base02
set-option -g pane-active-border-fg colour240 #base01

# message text
set-option -g message-bg colour235 #base02
set-option -g message-fg colour166 #orange

# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange

# clock
set-window-option -g clock-mode-colour colour64 #green
# Make tmux auto resurrect start on restart computer
set -g @resurrect-auto-tmux-start 'on'
set -g @resurrect-auto-restore 'on'


# VIM COPY AND PASTE BINDINGS BELOW.
# To enter copy mode, press {prefix} esc
# Use vim keybindings in copy mode
setw -g mode-keys vi
# Setup 'v' or 'V' to begin selection as in Vim
unbind [
bind Escape copy-mode

bind -t vi-copy v begin-selection
bind -t vi-copy V rectangle-toggle # `V` changes between line- and columnwise selection

# Clear scrollback. {prefix} Cntrl K
bind -n C-k clear-history


#Allow tmux Resurrect - prefix then ctrl-s to save. prefix then ctrl-r to restore
run-shell ~/.tmux/tmux-resurrect/resurrect.tmux
# Allow tmux to select text, etc.
run-shell ~/.tmux/tmux-copycat/copycat.tmux
# tmux yank. Enable copy selected text to the clipboard. Needs the above with prefix + y.
run-shell ~/.tmux/tmux-yank/yank.tmux
# MUST BE LAST COMMAND RUN: Auto run tmux ressurect every 15 minutes and auto ressurect when opening a new window
run-shell ~/.tmux/tmux-resurrect-auto/resurrect_auto.tmux


# Commands cheatsheet
# Within tmux
# prefix + ?: see all potential commands within tmux
# prefix + s: switch to a new session
# prefix + z: make the current pane take up the whole window. Toggleable.
# prefix + cntrl o: rotate window
# prefx + cntrl k: clear any text in the pane that is currently not visable.
# prefix + ctrl s: save all current sessions
# prefix + ctrl r: restore all current sessions from the last save point (eg. after a computer restart)
# prefix + Escape: enter copy mode
# - v: enter vim selection so you can copy.
# -- V: toggle back and fourth betmween block copy mode.
# - y: copy current selection to the clipboard.
# prefix + /: enter search mode for tmux pane
# prefix + :rename: allow you to rename the current session
# prefix + d: dettach the current session without ending it.
# prefix + x: close the current pane
# prefix + &: close the current window
# prefx + %: horizontal split
# prefix + ": vertical split
# In the terminal:
# man tmux: see all potential commands within tmux
# tmux a -t SESSIONNAMEORNUMEBR: re open that session
# tmux list-sessions: lists all the sessions available to be connected to
# tmux kill-server: kill all live sessions
```

**Comment by chiedojohn** [comment]
I also installed tmux with homebrew... I don't know if that would matter though... I'm wondering if it's a permissions error.

**Comment by bruno-** [comment]
Installing with homebrew should be okay.
I just tried removing `Tmux.Source.plist`, used your `tmux.conf`, re-loaded and the file appeared where it should.

How about checking if `~/Library/LaunchAgents/` directory exists? The script presumes the dir is there, so if it doesn't exist - that would explain it.

If that's okay, what does executing this file from the shell do: `~/.tmux/tmux-resurrect-auto/scripts/handle_tmux_automatic_start/osx_enable.sh`

That's a script responsible only for creating `Tmux.Source.plist` file. If there's an error, executing that script from the shell should show it.

**Comment by chiedojohn** [comment]
That's great progress! 
For some reason, I was missing the handle_tmux_automatic_start directory. So I did a git pull and it's all there.

I restarted my computer and the terminal restarted but my saved tmux session was not resurrected. It was a brand new tmux session.

I'm assuming that it was supposed to do the equivalent of opening my terminal, running the ```tmux``` command and then entering ```cntrl + r```?

**Comment by bruno-** [comment]
Aaaah okay.. yea, this feature was added just a day or two ago.

> I'm assuming that it was supposed to do the equivalent of opening my terminal, running the tmux command and then entering cntrl + r?

Yes, that should've happened. If `set -g @resurrect-auto-restore 'on'` is on, the only other thing that could prevent it is having this file created `~/tmux_no_auto_restore`. If it exists in your home directory, please remove it.
I also presume the plain old manual restore is working with `prefix + Ctrl-r`?

**Comment by chiedojohn** [comment]
That makes sense about the feature being added a day or two ago... I need to pay more attention!

I never had ```~/tmux_no_auto_restore``` and still don't.

So at this point, it looks like ```set -g @resurrect-auto-tmux-start 'on'``` is working but ```set -g @resurrect-auto-restore 'on'``` is not... at least on my end.

And yep, prefix + Ctrl-r works like a charm.

**Comment by bruno-** [comment]
I see. Wanna try executing the "auto-restore" script manually? So, after fresh tmux start execute this: `~/.tmux/tmux-resurrect-auto/scripts/resurrect_auto_restore.sh`. It should start doing the restore.

If that works then how about some debugging? [These lines](https://github.com/tmux-plugins/tmux-resurrect-auto/blob/master/resurrect_auto.tmux#L68-70) start auto-restore when fresh tmux server is fired. Try changing them to this:

```bash
if just_started_tmux_server; then
  touch ~/Desktop/dummy_file.txt         # this line added
  start_auto_restore_in_background
fi
```

After fresh tmux server start, you should see empty "dummy_file.txt" on your OS X desktop. That means "auto_restore" script is also called.

Another debugging thing we can try is changing [this line](https://github.com/tmux-plugins/tmux-resurrect-auto/blob/master/resurrect_auto.tmux#L52). Just remove the ampersand char at the end (auto restore will not happen in background, but immediately). Again, see what happens after fresh tmux start.

If all of the above works, then I dunno. The last thing that comes to mind is - do you maybe have a space character in your OS X username? So that the command `echo $PWD` returns a path with a space in it?

**Comment by chiedojohn** [comment]
Here are my findings.

If I start tmux a new tmux session an then run ```prefix + cntrl r``` then press ```ctrl d``` then run ```tmux``` then run ```~/.tmux/tmux-resurrect-auto/scripts/resurrect_auto_restore.sh``` the resurrect script works.
The good news is that all of the above did not work.

If I start a new tmux session and then run ```~/.tmux/tmux-resurrect-auto/scripts/resurrect_auto_restore.sh``` I see a notice that the resurrection worked but nothing happens.

I also noticed that the ```just_started_tmux_server``` function never gets called in the following
```
if just_started_tmux_server; then
	start_auto_restore_in_background
fi
```
I added ```touch ~/Desktop/test.txt``` inside the if statement and nothing happened but when I added ```touch ~/Desktop/test.txt``` before the if statement, the file was created.

And nope, no space characters in my username.
 
Lastly, removing the ampersand character had no effect.

**Comment by bruno-** [comment]
Hi, thank you for all the help. It seems there's an error in `just_started_tmux_server` function..
I installed tmux `1.9a` from homebrew and can reproduce the issue. I should've done this earlier.
I was using "edge" tmux (v2.0) the whole time and things work there.

I'll try to fix this and let you know when it works on `1.9a`.

**Comment by bruno-** [comment]
Hey - so I think the bug is now fixed. Here's the commit ee2f34b7ccbfae2060 that does the trick. I've tested this on tmux `1.9a` and it works now.

Can you update the plugin and let me know if it works for you? (I'm kinda excited to hear if this is fixed for good now)

**Comment by chiedojohn** [comment]
Issue continued on https://github.com/tmux-plugins/tmux-continuum/issues/1
